DROP TABLE IF EXISTS stat_hits CASCADE;

CREATE TABLE IF NOT EXISTS stat_hits (
                                         id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                         app_name     VARCHAR(100),
                                         uri_name     VARCHAR(255),
                                         ip_address   VARCHAR(30),
                                         create_time  TIMESTAMP
);
